version = 1

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/serhanoztuna/Coldfusion-Java-Benchmark"

[[analyzers]]
name = "kotlin"

  [analyzers.meta]
  runtime_version = "1.8"
  language_version = "1.7"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"